import { useState, useEffect } from "react";
import { SUBS, modColor } from "../data/data";

const getAiRisk = similarity => {
  if (similarity > 75) return { text: '🔴 Highly likely AI‑generated', color: '#EF4444' };
  if (similarity > 50) return { text: '🟠 Possible AI assistance',     color: '#F59E0B' };
  return                      { text: '🟢 Likely human‑written',       color: '#10B981' };
};

const escapeHtml = text => {
  if (!text) return '';
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
};

const getSubmissionDetails = studentName => {
  const sub = SUBS.find(s => s.studentName.toLowerCase() === studentName.toLowerCase());
  return { module: sub?.module || 'Unknown', title: sub?.title || 'Untitled', code: sub?.code || '' };
};

const INITIAL_REPORTS = [
  { id:1, student1:'Sara Moussaoui', student2:'Amine Touati',  similarity:87, date:'2024-03-27' },
  { id:2, student1:'Lyna Haddad',    student2:'Nour Khelifi',  similarity:73, date:'2024-03-26' },
];

export default function Plagiarism() {
  const [reports, setReports]             = useState(INITIAL_REPORTS);
  const [selectedReport, setSelectedReport] = useState(null);
  const [showModal, setShowModal]         = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem('plagiarismReport');
    if (saved) {
      const report = JSON.parse(saved);
      const sub = SUBS.find(s => s.studentName === report.studentName);
      if (sub) { report.code = sub.code; report.module = sub.module; report.title = sub.title; }
      setSelectedReport(report);
      setShowModal(true);
      localStorage.removeItem('plagiarismReport');
    }
  }, []);

  const downloadReport = report => {
    const studentName = report.studentName || report.student1;
    const studentId   = report.studentId   || 'N/A';
    const similarity  = report.similarity;
    const { module: mod, title, code: origCode } = getSubmissionDetails(studentName);
    const code    = report.code  || origCode || 'No code available';
    const subTitle = report.title || title;
    const date    = report.date  || new Date().toISOString().slice(0, 10);
    const aiRisk  = getAiRisk(similarity);
    const simColor = similarity > 70 ? '#EF4444' : similarity > 30 ? '#F59E0B' : '#10B981';

    const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Report - ${escapeHtml(studentName)}</title>
<style>body{font-family:Inter,sans-serif;background:#F8FAFC;padding:40px 20px;color:#1F2937}.container{max-width:900px;margin:0 auto;background:white;border-radius:24px;box-shadow:0 20px 35px -10px rgba(0,0,0,.1);overflow:hidden}.header{background:linear-gradient(135deg,#0F172A,#1E293B);color:white;padding:32px 40px;border-bottom:4px solid #FFC533}.header h1{font-size:28px;font-weight:800;margin-bottom:8px}.content{padding:40px}.info-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:24px;margin-bottom:32px;background:#F9FAFB;padding:24px;border-radius:16px}.info-label{font-size:12px;font-weight:600;text-transform:uppercase;color:#6B7280}.info-value{font-size:18px;font-weight:700;color:#111827;margin-top:4px}.sim-section{margin-bottom:32px;background:#FEF3F2;padding:24px;border-radius:16px;border-left:4px solid ${simColor}}.sim-value{font-size:48px;font-weight:800;color:${simColor}}.sim-bar{margin-top:12px;height:8px;background:#E5E7EB;border-radius:10px;overflow:hidden}.sim-fill{width:${similarity}%;height:100%;background:${simColor};border-radius:10px}pre{background:#1E1E2E;color:#E0E0E0;padding:20px;border-radius:12px;font-family:monospace;font-size:13px;line-height:1.5;white-space:pre-wrap}footer{background:#F9FAFB;padding:20px 40px;text-align:center;font-size:12px;color:#9CA3AF;border-top:1px solid #E5E7EB}@media print{button{display:none}}</style>
</head><body><div class="container">
<div class="header"><h1>📋 Plagiarism &amp; AI Detection Report</h1><p>Generated by ESIcodeHub</p></div>
<div class="content">
<div class="info-grid">
  <div><div class="info-label">Student</div><div class="info-value">${escapeHtml(studentName)}</div></div>
  <div><div class="info-label">Student ID</div><div class="info-value">${escapeHtml(studentId)}</div></div>
  <div><div class="info-label">Module</div><div class="info-value">${escapeHtml(mod)}</div></div>
  <div><div class="info-label">Title</div><div class="info-value">${escapeHtml(subTitle)}</div></div>
  <div><div class="info-label">Date</div><div class="info-value">${escapeHtml(date)}</div></div>
</div>
<div class="sim-section"><div style="font-size:14px;font-weight:600;margin-bottom:12px">⚠️ Similarity Score</div>
<div class="sim-value">${similarity}%</div>
<div class="sim-bar"><div class="sim-fill"></div></div>
<p style="margin-top:12px;font-size:13px;color:#4B5563">${similarity > 70 ? 'High risk – immediate review required.' : similarity > 30 ? 'Medium risk – further inspection recommended.' : 'Low risk – likely original work.'}</p></div>
<div style="margin-bottom:32px;background:#F0F9FF;padding:24px;border-radius:16px;border-left:4px solid ${aiRisk.color}">
<div style="font-size:14px;font-weight:600;margin-bottom:12px">🤖 AI Generation Likelihood</div>
<div style="font-size:24px;font-weight:800;color:${aiRisk.color}">${aiRisk.text}</div></div>
<div><div style="font-size:16px;font-weight:700;margin-bottom:12px">📄 Code Snippet</div>
<pre><code>${escapeHtml(code)}</code></pre></div></div>
<footer><p>© 2025–2026 ESIcodeHub · Confidential Academic Report</p></footer>
</div><div style="text-align:center;margin-top:20px"><button onclick="window.print()" style="background:#3B5BDB;color:white;border:none;padding:8px 16px;border-radius:8px;cursor:pointer">🖨️ Print Report</button></div>
</body></html>`;

    const a = Object.assign(document.createElement('a'), {
      href: URL.createObjectURL(new Blob([html], { type: 'text/html' })),
      download: `Plagiarism_Report_${studentName.replace(/\s/g, '_')}.html`,
    });
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
    URL.revokeObjectURL(a.href);
    alert(`📄 Report downloaded for ${studentName}`);
  };

  return (
    <div className="page-container">
      <div className="page-header">
        <h1>⚠️ Plagiarism Reports</h1>
        <button className="filter-btn" onClick={() => alert('Generate new report')}>📄 Generate Report</button>
      </div>

      <div className="stats-cards">
        {[
          ['🔴', reports.filter(r => r.similarity > 70).length,                    'High Risk'],
          ['🟠', reports.filter(r => r.similarity > 30 && r.similarity <= 70).length, 'Medium Risk'],
          ['🟢', reports.filter(r => r.similarity <= 30).length,                   'Low Risk'],
          ['📊', reports.length,                                                    'Total'],
        ].map(([icon, val, label]) => (
          <div key={label} className="stat-card">
            <div className="stat-icon">{icon}</div>
            <div><div className="stat-value">{val}</div><div className="stat-label">{label}</div></div>
          </div>
        ))}
      </div>

      <table className="data-table">
        <thead>
          <tr>
            <th>📄 STUDENT</th><th>📖 MODULE</th><th>📄 COMPARED WITH</th>
            <th>⚠️ SIMILARITY</th><th>📅 DATE</th><th>⚡ ACTION</th>
          </tr>
        </thead>
        <tbody>
          {reports.map(r => {
            const { module: mod } = getSubmissionDetails(r.student1);
            const sc = r.similarity > 70 ? '#EF4444' : r.similarity > 30 ? '#F59E0B' : '#10B981';
            return (
              <tr key={r.id}>
                <td><strong>{r.student1}</strong></td>
                <td><span style={{ ...modColor(mod), padding:'4px 10px', borderRadius:20, fontSize:12, fontWeight:600 }}>{mod}</span></td>
                <td>{r.student2}</td>
                <td>
                  <div className="similarity">
                    <div className="bar"><div className="fill" style={{ width:`${r.similarity}%`, background:sc }} /></div>
                    <span>{r.similarity}%</span>
                  </div>
                </td>
                <td>{r.date}</td>
                <td><button className="review-btn" onClick={() => downloadReport(r)}>📥 Download</button></td>
              </tr>
            );
          })}
        </tbody>
      </table>

      {showModal && selectedReport && (
        <div className="modal" onClick={() => setShowModal(false)}>
          <div className="modal-content" onClick={e => e.stopPropagation()} style={{ maxWidth:550 }}>
            <button className="close" onClick={() => setShowModal(false)}>✕</button>
            <h2 style={{ marginBottom:20 }}>📋 Plagiarism Report</h2>
            <div className="review-info">
              <p><strong>Student:</strong> {selectedReport.studentName} ({selectedReport.studentId})</p>
              <p><strong>Title:</strong> {selectedReport.title}</p>
              <p><strong>Module:</strong> {selectedReport.module}</p>
              <p><strong>Similarity:</strong> <span style={{ color: selectedReport.similarity > 70 ? '#EF4444' : selectedReport.similarity > 30 ? '#F59E0B' : '#10B981', fontWeight:'bold', fontSize:20 }}>{selectedReport.similarity}%</span></p>
            </div>
            <div className="code-section">
              <h3>📄 Code Snippet</h3>
              <pre className="code-preview">{selectedReport.code?.substring(0, 500) || 'No code available'}</pre>
            </div>
            <div className="modal-buttons">
              <button className="approve" onClick={() => { downloadReport(selectedReport); setShowModal(false); }}>📥 Download Report</button>
              <button className="changes" onClick={() => setShowModal(false)}>Close</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}